// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Otklik.Infrastructure.Persistence;

#nullable disable

namespace Otklik.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OtklikDbContext))]
    partial class OtklikDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("otklik")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Analytics.AnalyticsExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("PeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId", "CreatedAt");

                    b.ToTable("AnalyticsExports", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Analytics.AnalyticsOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<int>("AppealVersion")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("LastPublishError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppealId", "AppealVersion");

                    b.HasIndex("PublishedAt", "OccurredAt");

                    b.ToTable("AnalyticsOutboxMessages", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Analytics.AppealAnalyticsProjection", b =>
                {
                    b.Property<Guid>("AppealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("AssignedExpertId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CrisisFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ExpertGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstExpertResponseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastAppealVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LastAssignedExpertId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OperatorAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("ReturnCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("AppealId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LastAssignedExpertId");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("AppealAnalyticsProjections", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Analytics.ProcessedAnalyticsEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("AppealId", "ProcessedAt");

                    b.ToTable("ProcessedAnalyticsEvents", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AdminAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppealId", "Type", "ResolvedAt");

                    b.ToTable("AdminAlerts", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AdministrativeAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAt", "Action");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AdministrativeAuditEvents", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.Appeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("AppliedExpertGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppliedRoutingRuleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AppliedRoutingRuleVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedExpertId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientContinuationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CrisisDetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CrisisFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Narrative")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Standard");

                    b.Property<string>("PublicResolution")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RejectionInternalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ReturnCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("SubmissionPath")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AssignedExpertId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.HasIndex("ThreadId", "ClientContinuationId")
                        .IsUnique();

                    b.HasIndex("ThreadId", "Sequence")
                        .IsUnique();

                    b.HasIndex("Status", "CrisisFlag", "Priority", "CreatedAt");

                    b.ToTable("Appeals", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AppealId", "QuestionCode")
                        .IsUnique();

                    b.ToTable("AppealAnswers", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAssignmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ExpertUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("WorkflowRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ExpertUserId");

                    b.HasIndex("WorkflowRequestId");

                    b.HasIndex("AppealId", "OccurredAt");

                    b.ToTable("AppealAssignmentEvents", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientUploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("AppealId", "ClientUploadId")
                        .IsUnique();

                    b.ToTable("AppealAttachments", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AppealCategories", "otklik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "bullying",
                            DisplayName = "Травля",
                            IsActive = true,
                            SortOrder = 10,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "conflict",
                            DisplayName = "Конфликт",
                            IsActive = true,
                            SortOrder = 20,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "pressure",
                            DisplayName = "Давление",
                            IsActive = true,
                            SortOrder = 30,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "unsure",
                            DisplayName = "Не знаю, как это назвать",
                            IsActive = true,
                            SortOrder = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientComplaintId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppealId");

                    b.HasIndex("ClientComplaintId")
                        .IsUnique();

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("ResolvedAt", "CreatedAt");

                    b.ToTable("AppealComplaints", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealCrisisContact", b =>
                {
                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppealId");

                    b.ToTable("AppealCrisisContacts", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealDeviceGrant", b =>
                {
                    b.Property<Guid>("DeviceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceSessionId", "ThreadId");

                    b.HasIndex("ThreadId", "RevokedAt");

                    b.ToTable("AppealDeviceGrants", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealDeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("RevokedAt", "ExpiresAt");

                    b.ToTable("AppealDeviceSessions", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealExpertParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpertUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ExpertUserId");

                    b.HasIndex("RemovedByUserId");

                    b.HasIndex("AppealId", "ExpertUserId", "RemovedAt");

                    b.ToTable("AppealExpertParticipants", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealInternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ClientNoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("AppealId", "ClientNoteId")
                        .IsUnique();

                    b.HasIndex("AppealId", "CreatedAt");

                    b.ToTable("AppealInternalNotes", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("AppealId", "ClientMessageId")
                        .IsUnique();

                    b.HasIndex("AppealId", "CreatedAt");

                    b.ToTable("AppealMessages", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealNotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppealId");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("AppealNotificationOutboxes", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EndpointCiphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<byte[]>("EndpointHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dhCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceSessionId");

                    b.HasIndex("EndpointHash")
                        .IsUnique();

                    b.HasIndex("ThreadId", "RevokedAt");

                    b.ToTable("AppealPushSubscriptions", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid>("ClientRecommendationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("AppealId", "ClientRecommendationId")
                        .IsUnique();

                    b.HasIndex("AppealId", "Version")
                        .IsUnique();

                    b.ToTable("AppealRecommendations", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealResultFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientFeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppealId")
                        .IsUnique();

                    b.HasIndex("ClientFeedbackId")
                        .IsUnique();

                    b.ToTable("AppealResultFeedbacks", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealRoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpertGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("ExpertGroupId");

                    b.ToTable("AppealRoutingRules", "otklik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpertGroupId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000003"),
                            ExpertGroupId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000004"),
                            ExpertGroupId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            ExpertGroupId = new Guid("30000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("AppealId", "ChangedAt");

                    b.ToTable("AppealStatusChanges", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentCycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TrackHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("TrackRecoveryCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CurrentCycleId");

                    b.HasIndex("TrackHash")
                        .IsUnique();

                    b.ToTable("AppealThreads", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ApplicantOutcomeAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ReturnSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ClientActionId")
                        .IsUnique();

                    b.HasIndex("AppealId", "CreatedAt");

                    b.ToTable("ApplicantOutcomeActions", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.CrisisContactAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("AppealId", "AccessedAt");

                    b.ToTable("CrisisContactAccessLogs", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.CrisisMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Pattern")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("CrisisMarkers", "otklik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Pattern = "меня избива*",
                            RiskType = "PhysicalViolence",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Pattern = "меня бьют",
                            RiskType = "PhysicalViolence",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Pattern = "ударил* меня",
                            RiskType = "PhysicalViolence",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Pattern = "угрожа* уб*",
                            RiskType = "LifeThreat",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Pattern = "меня убьют",
                            RiskType = "LifeThreat",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Pattern = "напал* нож*",
                            RiskType = "LifeThreat",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Pattern = "хочу умер*",
                            RiskType = "SuicideRisk",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Pattern = "не хочу жить",
                            RiskType = "SuicideRisk",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            Pattern = "покончи* с собой",
                            RiskType = "SuicideRisk",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Pattern = "убью себя",
                            RiskType = "SuicideRisk",
                            SortOrder = 100
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000011"),
                            IsActive = true,
                            Pattern = "самоубий*",
                            RiskType = "SuicideRisk",
                            SortOrder = 110
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000012"),
                            IsActive = true,
                            Pattern = "суицид*",
                            RiskType = "SuicideRisk",
                            SortOrder = 120
                        });
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.CrisisSupportContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DialNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DisplayNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("CrisisSupportContacts", "otklik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000001"),
                            Description = "Бесплатно и анонимно по России",
                            DialNumber = "88002000122",
                            DisplayName = "Детский телефон доверия",
                            DisplayNumber = "8-800-2000-122",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000002"),
                            Description = "С мобильного телефона",
                            DialNumber = "124",
                            DisplayName = "Короткий номер телефона доверия",
                            DisplayNumber = "124",
                            IsActive = true,
                            SortOrder = 20
                        });
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ExpertGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveAppealLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExpertGroups", "otklik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            ActiveAppealLimit = 5,
                            Code = "support",
                            DisplayName = "Психологическая поддержка",
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            ActiveAppealLimit = 5,
                            Code = "mediation",
                            DisplayName = "Медиация конфликтов",
                            IsActive = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ExpertGroupMembership", b =>
                {
                    b.Property<Guid>("ExpertGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpertUserId")
                        .HasColumnType("uuid");

                    b.HasKey("ExpertGroupId", "ExpertUserId");

                    b.HasIndex("ExpertUserId");

                    b.ToTable("ExpertGroupMemberships", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ExpertWorkflowRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("KeepPreviousAsCoExecutor")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedExpertUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedPriority")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AppealId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SelectedExpertUserId");

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("ExpertWorkflowRequests", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.OperatorActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromValue")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ToValue")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AppealId", "OccurredAt");

                    b.ToTable("OperatorActionLogs", "otklik");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PlatformSettings", "otklik");

                    b.HasData(
                        new
                        {
                            Key = "Appeal.AutoCloseDays",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "7"
                        });
                });

            modelBuilder.Entity("Otklik.Infrastructure.Identity.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "otklik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Otklik.Domain.Analytics.AnalyticsExport", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AdminAlert", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany()
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AdministrativeAuditEvent", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.Appeal", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedExpertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Otklik.Domain.Appeals.AppealCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Otklik.Domain.Appeals.AppealThread", "Thread")
                        .WithMany("Cycles")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAnswer", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("Answers")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAssignmentEvent", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ExpertUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.ExpertWorkflowRequest", null)
                        .WithMany()
                        .HasForeignKey("WorkflowRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealAttachment", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("Attachments")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealComplaint", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("Complaints")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealCrisisContact", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithOne("CrisisContact")
                        .HasForeignKey("Otklik.Domain.Appeals.AppealCrisisContact", "AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealDeviceGrant", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.AppealDeviceSession", "DeviceSession")
                        .WithMany("Grants")
                        .HasForeignKey("DeviceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.AppealThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceSession");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealExpertParticipant", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("ExpertParticipants")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ExpertUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealInternalNote", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("InternalNotes")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealMessage", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("Messages")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealNotificationOutbox", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", null)
                        .WithMany()
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealPushSubscription", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.AppealDeviceSession", "DeviceSession")
                        .WithMany()
                        .HasForeignKey("DeviceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.AppealThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceSession");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealRecommendation", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("Recommendations")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealResultFeedback", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithOne("ResultFeedback")
                        .HasForeignKey("Otklik.Domain.Appeals.AppealResultFeedback", "AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealRoutingRule", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.AppealCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.ExpertGroup", "ExpertGroup")
                        .WithMany()
                        .HasForeignKey("ExpertGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ExpertGroup");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealStatusChange", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealThread", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "CurrentCycle")
                        .WithMany()
                        .HasForeignKey("CurrentCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentCycle");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ApplicantOutcomeAction", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("OutcomeActions")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.CrisisContactAccessLog", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("CrisisContactAccesses")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ExpertGroupMembership", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.ExpertGroup", "ExpertGroup")
                        .WithMany()
                        .HasForeignKey("ExpertGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ExpertUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertGroup");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.ExpertWorkflowRequest", b =>
                {
                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("WorkflowRequests")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("SelectedExpertUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.OperatorActionLog", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Otklik.Domain.Appeals.Appeal", "Appeal")
                        .WithMany("OperatorActions")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.PlatformSetting", b =>
                {
                    b.HasOne("Otklik.Infrastructure.Identity.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.Appeal", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("AssignmentHistory");

                    b.Navigation("Attachments");

                    b.Navigation("Complaints");

                    b.Navigation("CrisisContact");

                    b.Navigation("CrisisContactAccesses");

                    b.Navigation("ExpertParticipants");

                    b.Navigation("InternalNotes");

                    b.Navigation("Messages");

                    b.Navigation("OperatorActions");

                    b.Navigation("OutcomeActions");

                    b.Navigation("Recommendations");

                    b.Navigation("ResultFeedback");

                    b.Navigation("StatusHistory");

                    b.Navigation("WorkflowRequests");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealDeviceSession", b =>
                {
                    b.Navigation("Grants");
                });

            modelBuilder.Entity("Otklik.Domain.Appeals.AppealThread", b =>
                {
                    b.Navigation("Cycles");
                });
#pragma warning restore 612, 618
        }
    }
}
